#!/usr/bin/env -S python3 -B

from pathlib import Path
import logging as log
log.basicConfig(format='%(filename)s:%(lineno)d:%(levelname)s:%(message)s',
                level=log.DEBUG)

from platforms.spike import Platform_Spike
from builder.impl_asm import Builder_ASM
from builder.impl_c import Builder_C
from testlist import TestList

import yaml
import os

ROOT_ENV = 'RISCV_RND_ROOT'
ROOT_DIR = os.environ.get(ROOT_ENV)

INFRA_ROOT = str(Path(__file__).parent.absolute())
CORPUS_ROOT = Path(INFRA_ROOT + "/../corpus").resolve()

def remove_prefix(text, prefix):
  if text.startswith(prefix):
    return text[len(prefix):]

def testlist_info(path):
  TL = remove_prefix(str(path), str(CORPUS_ROOT) + "/")
  stl = TL.split("/")
  test_type = stl[0]
  subdir_components = stl[1:len(stl) - 1]
  subdir = "/".join([test_type, "/".join(subdir_components)])
  return { 'subdir': subdir, 'type': test_type, 'path': str(path) }

if ROOT_DIR == None:
  log.error('"{}" environment varible is not set'.format(ROOT_ENV))
  exit(1)

CFG_PATH = os.path.join(ROOT_DIR, "share/config.yaml")
CFG = None
with open(CFG_PATH, 'r') as stream:
  log.debug("loading config file from {}".format(CFG_PATH))
  CFG = yaml.safe_load(stream)
  log.debug(CFG)

platforms = {}
platforms["spike"] = Platform_Spike(CFG);
builders = {}
builders["asm"] = Builder_ASM(CFG, platforms)
builders["c"] = Builder_C(CFG, platforms)
log.debug(builders)

log.info("tests root: {}".format(CORPUS_ROOT))
for path in sorted(CORPUS_ROOT.rglob("*.yaml")):
  log.debug("discovering testlist at {}".format(path))
  info = testlist_info(path)
  log.debug(info)
  BUILDER_TYPE = info['type'];
  TestList(builders[BUILDER_TYPE], info['path'], info['subdir'], os.getcwd())

